### ISSUE TITLE
Double quote on non EPL server

### ISSUE THREAD

**Issue by Tfloow** [Hokkaydo/EPLBot#77]
Hi, I have been experiencing a weird issue where the bot would double quote some of my texts when quotting on a non EPL discord server. 
Kind regards

**Comment by Hokkaydo** [comment]
Could you provide a procedure to reproduce the bug?
Best regards

**Comment by Tfloow** [comment]
![image](https://github.com/Hokkaydo/EPLBot/assets/88899420/f724c7ea-1f40-4961-83fd-8a955d82dc8f)
I simply clicked copy link to message then pasted it in a random channel and here it just double quoted me

**Comment by Hokkaydo** [comment]
Thanks for notifying

**Comment by Hokkaydo** [comment]
Fixed by itself (magic is everywhere :boom:)

**Comment by Tfloow** [comment]
slay like we say
