### ISSUE TITLE
[Feature Request] Allow the user executing a program to remove the code or output

### ISSUE THREAD

**Issue by SuperLanceur** [Hokkaydo/EPLBot#93]

**Comment by emecdelam** [comment]
regarding this issue, I'm not sure how you would like it to work, having a trash emoji similar to Texit or a button system like this :
![image](https://github.com/user-attachments/assets/1a9c8e0d-e29f-416f-9c0c-d476fc01fe7a)

also, should the deletion be time dependent aka you can't delete after 5 mins, if not it would mean that the user should be stored indefinitely in the db

**Comment by Hokkaydo** [comment]
I think the easier would be simply going with an optional parameter "hide_code" set by default to false

**Comment by Hokkaydo** [comment]
Implemented
